[package]
name = "apic"
version = "0.1.0"
edition = "2018"
authors = ["WangRunji <wangrunji0408@163.com>"]
license = "MIT/Apache-2.0"
description = "APIC (Advanced Programmable Interrupt Controller) for x86 kernel."

[dependencies]
x86 = "0.33"
bit_field = "0.10"
bitflags = "1.2"